package com.blueridgebinary.terra;

import android.content.ContentResolver;
import android.content.ContentValues;
import android.database.Cursor;
import android.net.Uri;
import android.os.Bundle;
import android.support.v4.app.LoaderManager;
import android.support.v4.content.AsyncTaskLoader;
import android.support.v4.content.Loader;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import com.blueridgebinary.terra.adapters.SessionCursorAdapter;
import com.blueridgebinary.terra.data.TerraDbContract;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

public class CreateProjectActivity extends AppCompatActivity implements LoaderManager.LoaderCallbacks<Cursor> {

    private static final String TAG = CreateProjectActivity.class.getSimpleName();
    private static final int SESSION_LOADER_ID = 0;

    EditText etEnterSessionName;
    EditText etEnterSessionNotes;
    RecyclerView mRecyclerView;
    private SessionCursorAdapter mAdapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_create_project);

        etEnterSessionName = (EditText) findViewById(R.id.et_enter_session_name);
        etEnterSessionNotes = (EditText) findViewById(R.id.et_enter_session_notes);
        mRecyclerView = (RecyclerView) findViewById(R.id.recycler_view_test_session);

        mRecyclerView.setLayoutManager(new LinearLayoutManager(this));
        mAdapter = new SessionCursorAdapter(this);
        mRecyclerView.setAdapter(mAdapter);

        // Initialize Loader for Session/Project Data
        // adding the below code to the button function for  testing
        getSupportLoaderManager().initLoader(SESSION_LOADER_ID, null, this);
    }

    @Override
    protected void onResume() {
        super.onResume();
        Log.d("LOADER-DEBUG","onResume() called!");
        getSupportLoaderManager().restartLoader(SESSION_LOADER_ID, null, this);
    }

    private String getDateTime() {
        SimpleDateFormat dateFormat = new SimpleDateFormat(
                "yyyy-MM-dd HH:mm:ss", Locale.getDefault());
        Date date = new Date();
        return dateFormat.format(date);
    }


    /**
     * Instantiates and returns a new AsyncTaskLoader with the given ID.
     * This loader will return task data as a Cursor or null if an error occurs.
     *
     * Implements the required callbacks to take care of loading data at all stages of loading.
     */
    @Override
    public Loader<Cursor> onCreateLoader(int id, final Bundle loaderArgs) {

        return new AsyncTaskLoader<Cursor>(this) {

            // Initialize a Cursor, this will hold all the task data
            Cursor mSessionData = null;

            // onStartLoading() is called when a loader first starts loading data
            @Override
            protected void onStartLoading() {
                if (mSessionData != null) {
                    // Delivers any previously loaded data immediately
                    deliverResult(mSessionData);
                } else {
                    // Force a new load
                    forceLoad();
                }
            }

            // loadInBackground() performs asynchronous loading of data
            @Override
            public Cursor loadInBackground() {
                // Will implement to load data

                // Query and load all task data in the background; sort by priority
                // [Hint] use a try/catch block to catch any errors in loading data

                try {
                    return getContentResolver().query(TerraDbContract.SessionEntry.CONTENT_URI,
                            null,
                            null,
                            null,
                            TerraDbContract.SessionEntry.COLUMN_CREATED);

                } catch (Exception e) {
                    Log.e(TAG, "Failed to asynchronously load data.");
                    e.printStackTrace();
                    return null;
                }
            }

            // deliverResult sends the result of the load, a Cursor, to the registered listener
            public void deliverResult(Cursor data) {
                mSessionData = data;
                super.deliverResult(data);
            }
        };

    }


    /**
     * Called when a previously created loader has finished its load.
     *
     * @param loader The Loader that has finished.
     * @param data The data generated by the Loader.
     */
    @Override
    public void onLoadFinished(Loader<Cursor> loader, Cursor data) {
        // FROM GOOGLE - Update the data that the adapter uses to create ViewHolders
        mAdapter.swapCursor(data);
    }

    /**
     * Called when a previously created loader is being reset, and thus
     * making its data unavailable.
     * onLoaderReset removes any references this activity had to the loader's data.
     *
     * @param loader The Loader that is being reset.
     */
    @Override
    public void onLoaderReset(Loader<Cursor> loader) {
        mAdapter.swapCursor(null);
    }


    // Methods for Button Clicks

    public void onClickCreateSession(View v) {
        String inputName = etEnterSessionName.getText().toString();
        String inputNotes = etEnterSessionNotes.getText().toString();
        String currentDatetime = getDateTime();

        if (inputName.length() == 0) return;

        ContentValues contentValues = new ContentValues();
        contentValues.put(TerraDbContract.SessionEntry.COLUMN_SESSIONNAME, inputName);
        contentValues.put(TerraDbContract.SessionEntry.COLUMN_NOTES, inputNotes);
        contentValues.put(TerraDbContract.SessionEntry.COLUMN_CREATED, currentDatetime);
        contentValues.put(TerraDbContract.SessionEntry.COLUMN_UPDATED, currentDatetime);

        // Insert the content values via a ContentResolver
        Uri uri = getContentResolver().insert(TerraDbContract.SessionEntry.CONTENT_URI, contentValues);

        // Display the URI that's returned with a Toast
        // [Hint] Don't forget to call finish() to return to MainActivity after this insert is complete
        if (uri != null) {
            Toast.makeText(getBaseContext(), uri.toString(), Toast.LENGTH_LONG).show();
        }

        getSupportLoaderManager().restartLoader(SESSION_LOADER_ID, null, this);

    }

    public void onClickDeleteSessions(View v) {
        int numDeleted = getContentResolver().delete(TerraDbContract.SessionEntry.CONTENT_URI,null,null);
        if (numDeleted > 0 ) {
            Toast.makeText(getBaseContext(),"Deleted "  + Integer.toString(numDeleted) + " rows.",
                    Toast.LENGTH_LONG).show();
        }
        getSupportLoaderManager().restartLoader(SESSION_LOADER_ID, null, this);
    }

}